class Languages {
  List<String> languages = [
    'Amharic',
    'Arabic',
    'Basque',
    'Bengali',
    'Portuguese(Brazil)'
        'Catalan',
    'Cherokee',
    'Chinese',
    'Croatian',
    'Czech',
    'Danish',
    'Dutch',
    'English',
    'Estonian',
    'Finnish',
    'French',
    'German',
    'Greek',
    'Gujarati',
    'Hebrew',
    'hindi',
    'Hungarian',
    'Icelandic',
    'Indonesian',
    'Italian',
    'japanese',
    'Kannada',
    'Korean',
    'Latvian',
    'Lithuanian',
    'Malay',
    'Malayalam',
    'marathi',
    'Portuguese',
    'Norwegian',
    'Polish',
    'Portuguese(Portugal)',
    'Romanian',
    'Russian',
    'Serbian',
    'Slovak',
    'Slovenian',
    'spanish',
    'Swahili',
    'Swedish',
    'Tamil',
    'Telugu',
    'Thai',
    'Turkish',
    'Urdu',
    'Ukrainian',
    'Vietnamese',
    'Welsh',
  ];
  Map<String, String> code = {
    'Amharic': 'am',
    'Arabic': 'ar',
    'Basque': 'eu',
    'Bengali': 'bn',
    'Portuguese(Brazil)': 'bg',
    'Catalan': 'ca',
    'Cherokee': 'chr',
    'Chinese': 'zh',
    'Croatian': 'hr',
    'Czech': 'cs',
    'Danish': 'da',
    'Dutch': 'nl',
    'English': 'en',
    'Estonian': 'et',
    'Finnish': 'fi',
    'French': 'fr',
    'German': 'de',
    'Greek': 'el',
    'Gujarati': 'gu',
    'Hebrew': 'iw',
    'hindi': 'hi',
    'Hungarian': 'hu',
    'Icelandic': 'is',
    'Indonesian': 'id',
    'Italian': 'it',
    'japanese': 'ja',
    'marathi': 'mr',
    'Kannada': 'kn',
    'Korean': 'ko',
    'Latvian': 'lv',
    'Lithuanian': 'lt',
    'Malay': 'ms',
    'Malayalam': 'ml',
    'Norwegian': 'no',
    'Polish': 'pl',
    'Portuguese(Portugal)': 'pt',
    'Romanian': 'ro',
    'Russian': 'ru',
    'Serbian': 'sr',
    'Slovak': 'sk',
    'Slovenian': 'sl',
    'spanish': 'es',
    'Swahili': 'sw',
    'Swedish': 'sv',
    'Tamil': 'ta',
    'Telugu': 'te',
    'Thai': 'th',
    'Turkish': 'tr',
    'Urdu': 'ur',
    'Ukrainian': 'uk',
    'Vietnamese': 'vi',
    'Welsh': 'cy',
  };
}